#!/bin/sh
mvn clean package && docker build -t ujala/customerMP .
docker rm -f customerMP 2>/dev/null || true && docker run -it --name customerMP -p 8080:8080 -p 4848:4848 -p 8181:8181 --name customerMP ujala/customerMP
