#!/bin/sh
mvn clean package && docker build -t ujala/departmentMp .
docker rm -f departmentMp 2>/dev/null || true && docker run -it --name departmentMp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name departmentMp ujala/departmentMp
