#!/bin/sh
#deploy="false"
deploy="true"

image=customerFront
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t ujala/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push ujala/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag ujala/${image}:1.0-SNAPSHOT ujala/${image}:latest
        docker push ujala/${image}:latest
    fi
fi