#!/bin/sh
mvn clean package && docker build -t ujala/customerFront .
docker rm -f customerFront 2>/dev/null || true && docker run -it --name customerFront -p 8080:8080 -p 4848:4848 -p 8181:8181 --name customerFront ujala/customerFront
