#!/bin/sh
mvn clean package && docker build -t ujala/employeeMP .
docker rm -f employeeMP 2>/dev/null || true && docker run -it --name employeeMP -p 8080:8080 -p 4848:4848 -p 8181:8181 --name employeeMP ujala/employeeMP
